framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enable session support
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_domain: null
        cookie_path: /
        save_path: 'redis://localhost:6379'
        gc_maxlifetime: 7200                             # 2 heures (optionnel mais utile)
        gc_probability: 0

    #php_errors:
    #    log: true