framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enable session support
    session:
        handler_id: session.handler.native_file   # IMPORTANT : force le handler fichier natif de Symfony
        cookie_secure: auto
        cookie_samesite: lax
        cookie_domain: null   # ou 'localhost' si besoin
        cookie_path: /
        save_path: '%kernel.project_dir%/var/sessions'   # sera respect√© maintenant
        gc_maxlifetime: 7200                             # 2 heures (optionnel mais utile)
        gc_probability: 1

    #php_errors:
    #    log: true